---
title: Outline Studio
timezone: Europe/Amsterdam
collections:
  notes:
    title: Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: notes
  values:
    layout: note
    author: ''
permalink: pretty
sass:
  sass_dir: _sass
  style: compact
excerpt_separator: "<!--more-->"
